name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
      - uses: thehanimo/pr-title-checker@v1.3.6
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
